# Generated by Django 2.2.4 on 2019-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post-bg.jpg', upload_to='post_pics'),
        ),
    ]
